- name: install
  yum: name=ntp state=installed

- name: configure
  copy: src=ntp.conf dest=/etc/ntp.conf
  notify: restart ntpd

- name: running and enabled
  service: name=ntpd state=started enabled=yes
