- name: exclude postgresql rpms from CentOS-Base.repo 
  copy: src=CentOS-Base.repo dest=/etc/yum.repos.d/CentOS-Base.repo

- name: install pgdg-centos93-9.3-1.noarch.rpm
  yum: name=http://yum.postgresql.org/9.3/redhat/rhel-6-x86_64/pgdg-centos93-9.3-1.noarch.rpm state=present
